name: Execucao Diaria
on:
  schedule:
    - cron: '0 10 * * *' # 07:00 da manh√£ no Brasil
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  relatorio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yfinance
      - name: Executando o Script de Commodities
        run: python main.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
